---
- name: Playbook to delete trust
  hosts: ipaserver
  become: true

  tasks:
    - name: ensure the trust is absent
      freeipa.ansible_freeipa.ipatrust:
        realm: windows.local
        state: absent
