download_url: https://galaxy.ansible.com/download/amazon-aws-3.0.0.tar.gz
format_version: 1.0.0
name: aws
namespace: amazon
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/amazon/aws/versions/3.0.0/
