---
- name: Privilege present example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure privilege Broad Privilege is present
    freeipa.ansible_freeipa.ipaprivilege:
      ipaadmin_password: SomeADMINpassword
      name: Broad Privilege
      description: Broad Privilege
