---
- name: Automember hostgroup absent example
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure hostgroup automember rule ipaservers is absent
    freeipa.ansible_freeipa.ipaautomember:
      ipaadmin_password: SomeADMINpassword
      name: ipaservers
      automember_type: hostgroup
      state: absent
