---
- name: Automember default hostgroup not set
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure automember default hostgroup is not set
    freeipa.ansible_freeipa.ipaautomember:
      ipaadmin_password: SomeADMINpassword
      automember_type: hostgroup
      default_group: ""
