---
- name: Automember hostgroup membership for all hosts rebuilt example
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure hostgroup membership for all hosts has been rebuilt
    freeipa.ansible_freeipa.ipaautomember:
      ipaadmin_password: SomeADMINpassword
      automember_type: hostgroup
      state: rebuilt
