---
- name: Automember hostgroup rule member present example
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure hostgroup automember condition is present
    freeipa.ansible_freeipa.ipaautomember:
      ipaadmin_password: SomeADMINpassword
      name: "My domain hosts"
      automember_type: hostgroup
      state: present
      action: member
      inclusive:
        - key: fqdn
          expression: ".*.mydomain.com"
