---
- name: Permission present example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure permission TestPerm1 is renamed to TestPermRenamed
    freeipa.ansible_freeipa.ipapermission:
      ipaadmin_password: SomeADMINpassword
      name: TestPerm1
      rename: TestPermRenamed
      state: renamed
