---
- name: Permission member present example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure permission is present with "User Administrators" privilege
    freeipa.ansible_freeipa.ipapermission:
      ipaadmin_password: SomeADMINpassword
      name: TestPerm1
      privilege: "User Administrators"
      action: member
