---
- name: Permission present example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure permission is present
    freeipa.ansible_freeipa.ipapermission:
      ipaadmin_password: SomeADMINpassword
      name: TestPerm1
      object_type: host
      right: all
