---
- name: Tests
  hosts: ipaserver
  become: no
  gather_facts: no

  tasks:
    - name: Retrieve data from assymetric vault with a private key file.
      freeipa.ansible_freeipa.ipavault:
        ipaadmin_password: SomeADMINpassword
        name: asymvault
        username: user01
        private_key_file: private.pem
        state: retrieved
      register: result
      no_log: true
    - name: Display retrieved data.
      debug:
        msg: "Data: {{ result.vault.data }}"
