---
- name: Playbook to manage an automount key
  hosts: ipaserver

  tasks:
  - name: Ensure aumount key TestKey is renamed to NewKeyName
    freeipa.ansible_freeipa.ipaautomountkey:
      ipaadmin_password: password01
      automountlocationcn: TestLocation
      automountmapname: TestMap
      automountkey: TestKey
      newname: NewKeyName
      state: renamed
