---
- name: Automount location present example
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure automount locations DMZ and internal are present
    freeipa.ansible_freeipa.ipaautomountlocation:
      ipaadmin_password: SomeADMINpassword
      name:
        - DMZ
        - internal
      state: present
