download_url: https://galaxy.ansible.com/download/azure-azcollection-1.11.0.tar.gz
format_version: 1.0.0
name: azcollection
namespace: azure
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.11.0
version_url: https://galaxy.ansible.com/api/v2/collections/azure/azcollection/versions/1.11.0/
