download_url: https://galaxy.ansible.com/download/ansible-netcommon-2.5.1.tar.gz
format_version: 1.0.0
name: netcommon
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.5.1
version_url: https://galaxy.ansible.com/api/v2/collections/ansible/netcommon/versions/2.5.1/
