---
- name: Playbook to handle hostgroups
  hosts: ipaserver
  become: yes

  tasks:
  - name: Rename host-group from `databases` to `datalake`
    freeipa.ansible_freeipa.ipahostgroup:
      ipaadmin_password: SomeADMINpassword
      name: databases
      rename: datalake
      state: renamed
