download_url: https://galaxy.ansible.com/download/community-aws-3.0.1.tar.gz
format_version: 1.0.0
name: aws
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.0.1
version_url: https://galaxy.ansible.com/api/v2/collections/community/aws/versions/3.0.1/
