---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  - name: Add user member brain to group sysops
    freeipa.ansible_freeipa.ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: sysops
      action: member
      user:
      - brain
