---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  - name: Add group members sysops and appops to group sysops
    freeipa.ansible_freeipa.ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: ops
      group:
      - sysops
      - appops
