---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  - name: Remove goups sysops, appops and ops
    freeipa.ansible_freeipa.ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: sysops,appops,ops
      state: absent
