download_url: https://galaxy.ansible.com/download/freeipa-ansible_freeipa-1.6.2.tar.gz
format_version: 1.0.0
name: ansible_freeipa
namespace: freeipa
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.6.2
version_url: https://galaxy.ansible.com/api/v2/collections/freeipa/ansible_freeipa/versions/1.6.2/
