---
- name: Server present example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure server "ipareplica1.exmple.com" is present
    freeipa.ansible_freeipa.ipaserver:
      ipaadmin_password: SomeADMINpassword
      name: ipareplica1.example.com
