---
- name: Server hidden example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure server "ipareplica1.example.com" is hidden
    freeipa.ansible_freeipa.ipaserver:
      ipaadmin_password: SomeADMINpassword
      name: ipareplica1.example.com
      hidden: True
