---
- name: Server absent example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure server "absent.example.com" is absent
    freeipa.ansible_freeipa.ipaserver:
      ipaadmin_password: SomeADMINpassword
      name: absent.example.com
      state: absent
