---
- name: Selfservice absent
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure selfservice "basic manager attributes" is absent
    freeipa.ansible_freeipa.ipaselfservice:
      ipaadmin_password: SomeADMINpassword
      name: "basic manager attributes"
      state: absent
