download_url: https://galaxy.ansible.com/download/community-crypto-2.2.1.tar.gz
format_version: 1.0.0
name: crypto
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.2.1
version_url: https://galaxy.ansible.com/api/v2/collections/community/crypto/versions/2.2.1/
